# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master


pool:
  vmImage: ubuntu-latest

steps:
- task: Application security testing@2020
  inputs:
    projectName: '$(cx.projectName)'
    enableProxy: false
    enableSastScan: true
    fullTeamName: '$(cx.teamName)'
    enableDependencyScan: true
    dependencyTenant: 'plugins'
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
